"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var messageController_1 = require("../controllers/messageController");
var authMiddleware_1 = require("../middlewares/authMiddleware");
var router = express_1.default.Router();
router.use(authMiddleware_1.authMiddleware);
router.get('/:chatId', messageController_1.allMessages);
router.post('/send', messageController_1.sendMessages);
exports.default = router;
